# Generated by Django 3.2.9 on 2021-11-20 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211120_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('account_id', models.TextField()),
                ('money_amount', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='dni',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('receiver_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_receiver_account', to='api.account')),
                ('transmitter_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_transmiter_account', to='api.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.user'),
        ),
    ]
